### ISSUE TITLE
missing ModuleOptions

### ISSUE THREAD

**Issue by yapengsoft** [wavezync/nuxt-vue3-google-signin#12]
![image](https://github.com/wavezync/nuxt-vue3-google-signin/assets/75244754/080d0ed8-e899-4cb4-b655-efe58386a218)
export { default } from './module' seems to be missing ModuleOptions

**Comment by kasvith** [comment]
Thanks for the report, will take a look at this

**Comment by kasvith** [comment]
im not sure whether this is allowed by nuxt module bundler, as I checked it process the final outcome
