### ISSUE TITLE
Link to documentation is broken

### ISSUE THREAD

**Issue by mrleblanc101** [wavezync/nuxt-vue3-google-signin#13]
Link to documentation and to Vue 3 plugin is broken: [vue3-google-signin](https://vue3-google-signin.syetalabs.io/)

**Comment by kasvith** [comment]
Hi @mrleblanc101 where did you see this link?

**Comment by mrleblanc101** [comment]
My bad, here: https://nuxt.com/modules/nuxt-vue3-google-signin

**Comment by mrleblanc101** [comment]
But it comes from the README, so the link in the README don't work

**Comment by kasvith** [comment]
Thanks @mrleblanc101 

Fixed it
