### ISSUE TITLE
Error with One Tap Login

### ISSUE THREAD

**Issue by yaowangmx** [wavezync/nuxt-vue3-google-signin#23]
`<script lang="ts" setup>
import { useOneTap, type CredentialResponse } from 'vue3-google-signin'

useOneTap({
  onSuccess: (response: CredentialResponse) => {
    console.log('Success:', response)
  },
  onError: () => console.error('Error with One Tap Login'),
  // options
})
</script>`

version: nuxt-vue3-google-signin@0.0.11

![image](https://github.com/wavezync/nuxt-vue3-google-signin/assets/17875101/97482541-3f7a-48b0-a479-c2bfc8ce99a1)

But if i use this link's code(https://stackblitz.com/edit/github-7tvhqt?file=nuxt.config.ts,app.vue), I can get access_token

**Comment by kasvith** [comment]
did you follow all the instructions correctly

**Comment by yaowangmx** [comment]
> did you follow all the instructions correctly

Yes

**Comment by jsony** [comment]
me too

**Comment by jsony** [comment]
@yaowangmx how do you fixed？

**Comment by yaowangmx** [comment]
> @yaowangmx how do you fixed？

I gave up this plugin and switched to using it instead vue3-google-login@2.0.26

**Comment by jsony** [comment]
> I gave up this plugin and switched to using it instead vue3-google-login@2.0.26

can you give me a link about vue3-google-login@2.0.26, i'm from china,thank you

**Comment by yaowangmx** [comment]
> vue3-google-login

咦，遇到老乡了

**Comment by jsony** [comment]
> > vue3-google-login
> 
> 咦，遇到老乡了

我就说你咋这会在线，看着像老乡 我vx: yangyao8 来真有缘 哈哈

**Comment by jsony** [comment]
> > vue3-google-login
> 
> 咦，遇到老乡了：https://www.npmjs.com/package/vue3-google-login

这个怎么用到nuxt啊，直接引入模块报错

**Comment by jsony** [comment]
> > > vue3-google-login
> > 
> > 
> > 咦，遇到老乡了：https://www.npmjs.com/package/vue3-google-login
> 
> 这个怎么用到nuxt啊，直接引入模块报错

解决了，非常感谢老乡，中国人帮助中国人 哈哈
![image](https://github.com/user-attachments/assets/1c14169d-f22b-45a1-94fc-59eb2dc1495f)

**Comment by kasvith** [comment]
Hi @jsony @yaowangmx 

https://stackblitz.com/edit/github-erar5n?file=app.vue

in here i've tried exact same code as in the documentation to setup OneTap login
it seems to work for me

**Comment by luoshushu** [comment]
+1 Error with One Tap Login

**Comment by mrniamster** [comment]
Popup not displaying

**Comment by kasvith** [comment]
this seems to be related to fedcm issue https://github.com/wavezync/vue3-google-signin/issues/74 

tracking it in main package
