### ISSUE TITLE
Documentation page  is not working

### ISSUE THREAD

**Issue by mrniamster** [wavezync/nuxt-vue3-google-signin#8]
1. The site https://vue3-google-signin.syetalabs.io/ is not working, can you please update the domain, also in nuxt modules page, facing problems to get started.

![image](https://github.com/kasvith/nuxt-vue3-google-signin/assets/52563039/7202fc88-c6a5-426e-908f-1d02429c93a6)

**Comment by kasvith** [comment]
Fixed https://vue3-google-signin.wavezync.com/
